# Super basic pylint action

name: pylint

# Run on commits/PRs onto master
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Set up a python3 env and run pylint
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'
      - run: pip install pylint  # -r requirements.txt
      - run: pylint --rcfile=.pylintrc $PWD
